
import "./globals.css";
import { ThemeProvider } from "@/provider/ThemeProvider";
import Navbar from "@/components/shared/Navbar";
import { Poppins } from 'next/font/google';
import Footer from "@/components/shared/Footer";


const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});




export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} antialiased dark:bg-[#1E1E1E]`}
      >
         <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Navbar />
            {children}
            <Footer />
          </ThemeProvider>
      
      </body>
    </html>
  );
}
